apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate	  
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      name: kuber-app
      labels:
        app: http-server
    spec:
      containers:
      - name: kuber-app-image
        image: bokovets/kuber:v1.0
        ports:
        - containerPort: 8000  
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec: 
  selector:
    matchLabels:
      app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP      